name: livedb
description: "Live DB Free Cloud Database & Storage for Flutter. Realtime NoSQL document database and instant file storage with encryption support. Liivedb is a  Firebase alternative.  #tags: livedbs database , storage , nosql , cloud , offline , firebase , free storage , live database, database storage ,  free database , live storage , cloud database , media storage , offline database , offline storage "
topics: 
  - livedb
  - live-storage
  - free-storage
  - firebase-storage
  - offline-database







version: 1.0.1

homepage: https://github.com/HassanAmeer/livedb_flutter_package
documentation: https://livedbs.web.app/api-docs
repository: https://github.com/HassanAmeer/livedb_flutter_package
issue_tracker: https://github.com/HassanAmeer/livedb_flutter_package/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  mime: ^1.0.0
  path: ^1.8.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

screenshots:
  - description: LiveDB Demo - Realtime DB & Storage
    path: screenshots/1.png


flutter:
